"""add scheduled_class table

Revision ID: 24f9cd69ac72
Revises: 5a2c580b928f
Create Date: 2026-09-21 16:33:50.786783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '24f9cd69ac72'
down_revision: Union[str, Sequence[str], None] = '5a2c580b928f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduledclass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('class_number', sa.Integer(), nullable=False),
    sa.Column('chapter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('focus', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheduled_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduledclass_user_id'), 'scheduledclass', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduledclass_user_id'), table_name='scheduledclass')
    op.drop_table('scheduledclass')
    # ### end Alembic commands ###
