"""add google account and note doc tables

Revision ID: 7a820515beab
Revises: 4229cba3d208
Create Date: 2026-10-01 19:41:31.734184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7a820515beab'
down_revision: Union[str, Sequence[str], None] = '4229cba3d208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('googleaccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('google_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_googleaccount_user_id'), 'googleaccount', ['user_id'], unique=True)
    op.create_table('notedoc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doc_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doc_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'grade', 'subject')
    )
    op.create_index(op.f('ix_notedoc_user_id'), 'notedoc', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notedoc_user_id'), table_name='notedoc')
    op.drop_table('notedoc')
    op.drop_index(op.f('ix_googleaccount_user_id'), table_name='googleaccount')
    op.drop_table('googleaccount')
    # ### end Alembic commands ###
