"""add calendar event id to scheduled class

Revision ID: 128984986a12
Revises: 7a820515beab
Create Date: 2026-10-01 19:55:51.453217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '128984986a12'
down_revision: Union[str, Sequence[str], None] = '7a820515beab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default so rows that already exist get "" rather than failing the
    # NOT NULL constraint. Kept in place: SQLite (local dev) cannot DROP
    # DEFAULT, and an empty-string default is harmless since the app always
    # sets this column explicitly.
    op.add_column(
        'scheduledclass',
        sa.Column(
            'calendar_event_id',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default='',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduledclass', 'calendar_event_id')
    # ### end Alembic commands ###
